"""empty message

Revision ID: e5b45e75134b
Revises: 
Create Date: 2021-08-04 09:56:26.594468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b45e75134b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_id', sa.String(length=120), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_e_id'), 'user', ['e_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_e_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
